=== RoseTec/JigSPuzzle/src/main/resources/languages/language.dtd
<!ELEMENT language (page*)>
<!ATTLIST language tag CDATA #REQUIRED>
<!-- the tag of a language is used to change the java environment of this execution to the desired language -->
<!-- see also: https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#forLanguageTag-java.lang.String- -->

<!ELEMENT page (t*)>
<!ATTLIST page id ID #REQUIRED>
<!ATTLIST page descr CDATA "">

<!ELEMENT t (#PCDATA)>
<!ATTLIST t id ID #REQUIRED>
<!ATTLIST t descr CDATA "">

=== RoseTec/JigSPuzzle/src/main/resources/languages/english.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "language.dtd">

<language tag="en">
    <page id="1" descr="puzzle window menu">
        <t id="1" descr="puzzle window title">JigSPuzzle</t>

        <t id="55">Puzzle could not be created.</t>
        <t id="56">No puzzle could be created from the given file.</t>

        <t id="100">Puzzle</t>
        <t id="110">Create New Puzzle</t>
        <t id="120">Load Old Puzzle</t>
        <t id="130">Save this Puzzle</t>
        <t id="150">Shuffle Puzzle</t>
        <t id="160">Restart Puzzle</t>
        <t id="180">Quit JigSPuzzle</t>

        <t id="300">Settings</t>
        <t id="310">Appearance-Settings</t>
        <t id="320">Puzzle-Options</t>

        <t id="500">About</t>
        <t id="510">About JigSPuzzle</t>
        <t id="520">Check New Version</t>
    </page>

    <page id="5" descr="ErrorMessageDialog">
        <t id="10">There was the following error:</t>
        <t id="20">close message</t>
    </page>

    <page id="10" descr="settings window">
        <t id="1" descr="settings window title">Settings</t>
        <t id="2">Save</t>
        <t id="3">Abort</t>

        <t id="11">Appearance</t>
        <t id="12">Puzzle</t>

        <t id="85">Settings could not be saved</t>
        <t id="86">The settings could not be saved.</t>
        <t id="87">Settings could not be loaded</t>
        <t id="88">The settings could not be loaded.</t>

        <t id="100">Language</t>
        <t id="101">Used Language for the interface:</t>

        <t id="120">Backgroundcolor</t>
        <t id="121">used color:</t>

        <t id="140">Preview</t>
        <t id="141">Show a preview of the complete puzzle</t>

        <t id="160">Size of the puzzle</t>
        <t id="161">Used Size for the puzzleare:</t>
        <t id="164">Keep aspect ratio</t>
        <t id="167">Decrease picture automatically</t>
        <t id="170">Enlarge picture automatically</t>

        <t id="180">Number of puzzlepieces</t>
        <t id="181">Number of puzzlepieces:</t>
        <t id="182">The number of puzzlepieces is an approximate value. It will be tried to divide the puzzle in the given number of pieces. Is this not possible, a number very near to this number will be choosen.</t>
        <t id="183">Changing this value is only visible when starting a new puzzle.</t>

        <t id="200">Snapping puzzlepieces</t>
        <t id="201">The distance that two puzzlepieces must have in order to let the puzzlepieces snap together.</t>
        <t id="202">small</t>
        <t id="203">big</t>
    </page>
</language>

=== RoseTec/JigSPuzzle/src/main/resources/languages/deutsch.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "language.dtd">

<language tag="de">
    <page id="1" descr="puzzle window menu">
        <t id="1" descr="puzzle window title">JigSPuzzle</t>

        <t id="51">Puzzle konnte nicht gespeichert werden.</t>
        <t id="52">Das Puzzle konnte nicht in die angegebene Datei gespeichert werden.</t>
        <t id="53">Puzzle konnte nicht geladen werden.</t>
        <t id="54">Das Puzzle konnte nicht aus der angegebenen Datei geladen werden.</t>
        <t id="55">Puzzle konnte nicht erstellt werden.</t>
        <t id="56">Aus der angegebenen Datei konnte kein Puzzle erstellt werden.</t>
        <t id="57">Puzzle konnte nicht neu gestarted werden.</t>
        <t id="58">Das Puzzle konnte nicht neu gestarted werden.</t>

        <t id="100">Puzzle</t>
        <t id="110">Neues Puzzle Erstellen</t>
        <t id="111">Alle Bilder</t>
        <t id="112">Bilder (*.bmp)</t>
        <t id="113">Bilder (*.gif)</t>
        <t id="114">Bilder (*.jpg)</t>
        <t id="115">Bilder (*.png)</t>
        <t id="120">Altes Puzzle Laden</t>
        <t id="121">JigsPuzzle Puzzles (*.jig)</t>
        <t id="130">Dieses Puzzle Speichern</t>
        <t id="150">Puzzle Durchmischen</t>
        <t id="160">Puzzle Neu Starten</t>
        <t id="180">JigSPuzzle Beenden</t>

        <t id="300">Einstellungen</t>
        <t id="310">Oberfläche</t>
        <t id="320">Puzzle</t>

        <t id="500">Über</t>
        <t id="510">Über JigSPuzzle</t>
        <t id="520">Auf Neue Version Prüfen</t>
    </page>

    <page id="5" descr="ErrorMessageDialog">
        <t id="10">Es trat folgender Fehler auf:</t>
        <t id="20">Nachricht schließen</t>
    </page>

    <page id="10" descr="settings window">
        <t id="1" descr="settings window title">Einstellungen</t>
        <t id="2">Speichern</t>
        <t id="3">Abbrechen</t>

        <t id="11">Oberfläche</t>
        <t id="12">Puzzle</t>

        <t id="85">Einstellungen wurden nicht gespeichert.</t>
        <t id="86">Die Einstellungen konnten nicht gespeichert werden.</t>
        <t id="87">Einstellungen wurden nicht geladen</t>
        <t id="88">Die Einstellungen konnten nicht geladen werden.</t>

        <t id="100">Sprache</t>
        <t id="101">Die verwendete Sprache für die Oberfläche:</t>

        <t id="120">Hintergrundfarbe</t>
        <t id="121">verwendete Farbe:</t>

        <t id="140">Vorschau</t>
        <t id="141">Zeige Vorschau des fertigen Puzzles an</t>

        <t id="160">Größe des Puzzles</t>
        <t id="161">Es wird er folgende Anteil der Puzzlefläche für die Größe des Puzzles verwendet:\nEin Wert von 75% bedeutet, dass das Puzle auf 75% der Größe der Puzzlefläche skaliert wird.</t>
        <t id="164">Behalte Seitenverhältnisse bei</t>
        <t id="167">Verkleinere Bild automatisch</t>
        <t id="170">Vergrößere Bild automatisch</t>

        <t id="180">Anzahl der Puzzleteile</t>
        <t id="181">Anzahl der Puzzleteile:</t>
        <t id="182">Die Anzahl an Puzzleteilen ist ein ungefährer Wert. Es wird versucht, das Puzzle in die angegebene Anzahl an Teilen zu zerteilen. Ist dies nicht möglich, wird eine Zahl sehr nahe an dieser Zahl gewählt.</t>
        <t id="183">Änderung dieses Wertes wird bei einem neuen Puzzle sichtbar.</t>

        <t id="200">Einrast-Größe</t>
        <t id="201">Der Abstand, den zwei Puzzleteile haben müssen, um einzurasten und somit als 'ineinander gesteckt' zu gelten</t>
        <t id="202">klein</t>
        <t id="203">groß</t>

        <t id="220">Sounds</t>
        <t id="222">Spiele Sounds ab</t>
    </page>

    <page id="11" descr="VersionDialog">
        <t id="1">JigSPuzzle</t>

        <t id="10">Diese Version:</t>
        <t id="11">Neueste verfügbare Version:</t>
        <t id="15">-suche-</t>

        <t id="20">Neue Version herunterladen</t>
        <t id="21">Dies ist bereits die aktuelle Version</t>
    </page>

</language>
